mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView





urlpatterns = [
    path('admin/', admin.site.urls),
	path('',include('users.urls')),
    
]+ static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

mysite/users/urls.py
from django.urls import include, path
from users.views import adoptantes
from users.views import fundacion
from django.conf import settings
from django.conf.urls.static import static

app_name = 'users'



urlpatterns = [
	path('reg/', adoptantes.AdoptSignUpView.as_view(),name="registro"),
	path('regf/',fundacion.FundtSignUpView.as_view(),name="registroFundacion"),
	path('log/',adoptantes.loginPage,name="login"),
	#path('main2/',adoptantes.vista_main_2,name="main2"),
	path('l/',adoptantes.logoutUser,name="logout"),

	path('main/',adoptantes.Catalogo.as_view(),name="main"),
	path('main/<int:pk>',adoptantes.CrearMatch.as_view(),name="match"),
	path('match/',adoptantes.SeleccionarMatch.as_view(),name="list_match"),
	path('match/<int:pk>',adoptantes.PerfilMascota.as_view(),name="perfil_mascota"),

	path('agregar/', fundacion.AgregarMascota.as_view(),name="agregar"),
	#path('editar/', fundacion.editar,name="editar"),
	path('eliminar/<int:pk>', fundacion.EliminarMascota.as_view(),name="eliminar"),
	path('eliminar/', fundacion.SeleccionarMascotaEliminar.as_view(),name="sel_eliminar"),

	path('seleccionar/', fundacion.SeleccionarMascota.as_view(),name="seleccionar"),
	path('editar/<int:pk>', fundacion.EditarMascota.as_view(), name='editar'),

	path('agregar_multimedia/<int:pk>', fundacion.AgregarMulti.as_view(), name='agregar_multi'),
	path('multimedia/<int:pk>', fundacion.VerMultimedia.as_view(), name='multimedia')
]+ static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

mysite/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.db import transaction

from users.models import usuarios,Fundacion,Mascota,Contenido_Multi, Match

class AdoptSignUpForm(UserCreationForm):
    correo = forms.EmailField(label="Correo electrónico")

    class Meta(UserCreationForm.Meta):
        model = usuarios
        fields = ["correo","nombre", "password1", "password2"]
    @transaction.atomic
    def save(self):
        user = super().save(commit=False)
        user.es_adoptante = True
        user.save()
        return user

class UserloginForm(AuthenticationForm):
    correo = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta:
        model = usuarios
        fields = ["correo","password"]


class FundacionSignUpForm(UserCreationForm):
    correo = forms.EmailField(label="Correo")
    nombre_fund = forms.CharField(max_length=20)
    info_fundacion = forms.CharField(max_length=50)
    list_ciudades = ((1,'Cali'),(2,'Palmira'))
    ciudad = forms.ChoiceField(choices=list_ciudades)
    class Meta(UserCreationForm.Meta):
        model = usuarios
        fields = ("correo","nombre_fund","info_fundacion","ciudad","password1","password2")
    def save(self):
        user = super().save(commit=False)
        user.es_fundacion=True
        user.save()        
        usuario_fund = Fundacion(
            usuario = user,
          nombre_fund = self.cleaned_data['nombre_fund'],
          info_fundacion = self.cleaned_data['info_fundacion'],
          ciudad = self.cleaned_data['ciudad']
            )
        # usuario.es_fundacion=True
        # usuario.save()
        usuario_fund.save()
        # print(usuario_fund)
        # return usuario 
        return user

class AgregarMascota(forms.ModelForm):
    class Meta():
        model = Mascota
        exclude = ("idfundacion",)
        fields = ("foto","Nombre","Descripcion","Tipo_Mascota","Edad","genero","Estado_salud","Estado_esterilzacion","ciudad")
        
        widgets = {
            'Nombre': forms.TextInput(attrs={'class': 'w3-input w3-border w3-light-grey'}),
            'Descripcion': forms.TextInput(attrs={'class': 'w3-input w3-border w3-light-grey'}),
            'Tipo_Mascota': forms.Select(attrs={'class': 'w3-input w3-border w3-light-grey'}),
            'Edad': forms.NumberInput(attrs={'class': 'w3-input w3-border w3-light-grey'}),
            'genero': forms.Select(attrs={'class': 'w3-input w3-border w3-light-grey'}),
            'Estado_salud': forms.TextInput(attrs={'class': 'w3-input w3-border w3-light-grey'}),
            'Estado_esterilzacion': forms.Select(attrs={'class': 'w3-input w3-border w3-light-grey'}),
            'ciudad': forms.Select(attrs={'class': 'w3-input w3-border w3-light-grey'})
        }
    
class AgregarMultimedia(forms.ModelForm):
    class Meta():
        model = Contenido_Multi
        exclude = ("id_mascota",)
        fields = ("tipo_contenido","titulo","descripcion","foto")
        
        widgets = {
            'descripcion': forms.TextInput(attrs={'class': 'w3-input w3-border w3-light-grey'}),
            'titulo': forms.TextInput(attrs={'class': 'w3-input w3-border w3-light-grey'}),
            'tipo_contenido': forms.Select(attrs={'class': 'w3-input w3-border w3-light-grey'}),
        }       

class NuevoMatch(forms.ModelForm):
    class Meta():
        model = Match
        exclude = ("Idusuario","IdMascota")
  

mysite/users/views.py
from django.shortcuts import render

# Create your views here.

mysite/users/views/adoptantes.py
from django.contrib.auth import login,authenticate, logout
from django.shortcuts import redirect,render
from django.views.generic import CreateView, ListView
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy, resolve

from ..models import usuarios


from ..models import Mascota
from ..models import Match
from ..models import Contenido_Multi
from ..forms import AdoptSignUpForm,UserloginForm, NuevoMatch
from ..decorators import adop_required


from ..forms import AdoptSignUpForm
#Create password to easy message


class AdoptSignUpView(CreateView):
    model = usuarios
    form_class = AdoptSignUpForm
    template_name = 'adoptantes/registro_adop.html'

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'adoptante'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        #print(user)
        login(self.request, user)
        return redirect('users:main')


#Todo-login view para adoptantes

#Todo-login view para adoptantes
def loginPage(request):
    if request.method == 'POST':
        correo = request.POST.get('correo')
        password = request.POST.get('password')
        user = authenticate(request,username=correo,password=password)
        #print(user.es_fundacion)
        if user is not None:
            login(request,user)
            if user.es_adoptante:
                return redirect('users:main')
            else:
                return redirect('users:agregar')
    context = {}
    return render(request,'adoptantes/login.html',context)


def logoutUser(request):
    logout(request)
    return redirect('users:login')




def vista_main_2(request):
    context = {}
    return render(request,'adoptantes/infoFundacion.html',context)

class Catalogo(ListView):

    model = Mascota
    template_name = 'adoptantes/catalogo.html'

    context_object_name = 'mascotas'
    paginate_by = 1

    #def get_context_data(self, *args, **kwargs):
     #   context = super().get_context_data(*args, **kwargs)
      #  context['info'] = Fundacion.objects.filter(usuario=self.request.user)
       # return context

    def get_queryset(self):
        q1 = Mascota.objects.all()
        q2 = Match.objects.filter(Idusuario=self.request.user)
        for i in q2:
            q1 = q1.exclude(id=i.IdMascota.id)
        
        return q1

class CrearMatch(CreateView):
    model = Match
    form_class = NuevoMatch
    template_name = 'adoptantes/match.html'

    def form_valid(self, form):
        form.instance.IdMascota = Mascota.objects.get(id=self.kwargs['pk'])
        form.instance.Idusuario = self.request.user
        return super().form_valid(form)

    success_url = reverse_lazy('users:main')

class SeleccionarMatch(ListView):

    model = Match
    template_name = 'adoptantes/mis_match.html'
    #queryset = Mascota.objects.filter(idfundacion="2")
    context_object_name = 'mascotas'
    paginate_by = 3

    def get_queryset(self):
        q1 = Mascota.objects.all()
        q2 = Match.objects.filter(Idusuario=self.request.user)
        for i in q2:
            q1 = q1.exclude(id=i.IdMascota.id)
        
        q3 = Mascota.objects.all()
        q1 = q3.difference(q1)
        print(q1)
        return q1

class PerfilMascota(ListView):

    model = Mascota
    template_name = 'adoptantes/perfil.html'
    #queryset = Mascota.objects.filter(idfundacion="2")
    context_object_name = 'multimedia'
    paginate_by = 3

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['info'] = Mascota.objects.filter(id=self.kwargs['pk'])
        return context

    def get_queryset(self):
        return Contenido_Multi.objects.filter(id_mascota=self.kwargs['pk'])
        

mysite/users/views/fundacion.py
from django.contrib.auth import login,authenticate
from django.shortcuts import redirect,render
from django.urls import reverse_lazy, resolve
from django.views.generic import CreateView, ListView, DeleteView
from django.views.generic.edit import UpdateView
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse 
from django.shortcuts import get_object_or_404
from ..models import usuarios, Fundacion, Mascota, Match, Contenido_Multi
from ..forms import AdoptSignUpForm, AgregarMascota, AgregarMultimedia,FundacionSignUpForm

from django.contrib.messages.views import SuccessMessageMixin



class FundtSignUpView(CreateView):
    model = usuarios
    form_class = FundacionSignUpForm
    template_name = 'fundacion/registro_f.html'

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'fundacion'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        #print(user)
        login(self.request, user)
        return redirect('users:agregar')
"""
def agregar(request):

	info = Fundacion.objects.filter(nombre_fund="2")
	if request.method == 'POST':
		form = AgregarMascota(request.POST or None, request.FILES or None)
		
		print(form.errors)
		if form.is_valid():
			post = form.save(commit=False)
			post.idfundacion = info[0]
			post.save()

	form = AgregarMascota()
	context ={'info':info,'form':form}
	return render(request,'fundacion/agregar.html',context) 



def editar(request,id_mascota):
	info = Fundacion.objects.filter(nombre_fund="2")
	mascota = Mascota.objects.get(id=id_mascota)
	if request.method == 'POST':
		mascota.Nombre = request.POST.get('Nombre')
		mascota.Descripcion = request.POST.get('Descripcion')
		mascota.Edad = request.POST.get('Edad')
		mascota.genero = request.POST.get('genero')
		mascota.Tipo_Mascota = request.POST.get('Tipo_Mascota')
		mascota.Estado_esterilzacion = request.POST.get('Estado_esterilzacion')
		mascota.Estado_salud = request.POST.get('Estado_salud')
		mascota.ciudad = request.POST.get('ciudad')
		mascota.foto = request.FILES.get('foto')
		mascota.save()

	form = AgregarMascota(initial={"Nombre":mascota.Nombre,
									"Descripcion":mascota.Descripcion,
									"Edad":mascota.Edad,
									"genero":mascota.genero,
									"Tipo_Mascota":mascota.Tipo_Mascota,
									"Estado_esterilzacion":mascota.Estado_esterilzacion,
									"Estado_salud":mascota.Estado_salud,
									"ciudad":mascota.ciudad,
									"foto":mascota.foto,
									"idfundacion":info[0]})
	context ={'info':info,'form':form}
	return render(request,'fundacion/editar.html',context)


def eliminar_final(request,id_mascota):
	info = Fundacion.objects.filter(nombre_fund="2")
	if request.method == 'POST':

		Mascota.objects.filter(id=id_mascota).delete()
		mascotas = Mascota.objects.filter(idfundacion="2")
		return redirect('users:eliminar')

	context ={'info':info, 'mascotas':Mascota.objects.filter(id=id_mascota)}
	return render(request,'fundacion/eliminar_final.html',context)

def eliminar(request):
	info = Fundacion.objects.filter(nombre_fund="2")
	mascotas = Mascota.objects.filter(idfundacion="2")
	if request.method == 'POST':
		mascota_id = request.POST.get('id')
		return redirect('eliminar_final',mascota_id)
	context ={'info':info, 'mascotas':mascotas}
	return render(request,'fundacion/eliminar.html',context)
	

def seleccionar(request):
	info = Fundacion.objects.filter(nombre_fund="2")
	mascotas = Mascota.objects.filter(idfundacion="2")
	if request.method == 'POST':
		mascota_id = request.POST.get('id')
		return redirect('editar',mascota_id)
	context ={'info':info, 'mascotas':mascotas}
	return render(request,'fundacion/seleccionar.html',context)
"""
# Clases 

class EditarMascota(SuccessMessageMixin, UpdateView):
	model = Mascota
	form_class = AgregarMascota
	template_name = 'fundacion/editar.html'
	context_object_name = 'mascotas'
	success_message = "Mascota Editada Correctamente!"

	def get_queryset(self):
		return Mascota.objects.filter(id=self.kwargs['pk'])
	def get_context_data(self, *args, **kwargs):
		context = super().get_context_data(*args, **kwargs)
		context['info'] = Fundacion.objects.filter(usuario=self.request.user)
		return context

    
	success_url = reverse_lazy('users:seleccionar')

class EliminarMascota(SuccessMessageMixin, DeleteView):
	model = Mascota
	template_name = 'fundacion/eliminar_final.html'
	context_object_name = 'mascotas'
	success_message = "Mascota Eliminada Correctamente!"

	


	def get_context_data(self, *args, **kwargs):
		context = super().get_context_data(*args, **kwargs)
		context['info'] = Fundacion.objects.filter(usuario=self.request.user)
		return context

	success_url = reverse_lazy('users:sel_eliminar')

class SeleccionarMascotaEliminar(ListView):

	model = Mascota
	template_name = 'fundacion/eliminar.html'
	#queryset = Mascota.objects.filter(idfundacion="2")
	context_object_name = 'mascotas'
	paginate_by = 3

	def get_context_data(self, *args, **kwargs):
		context = super().get_context_data(*args, **kwargs)
		context['info'] = Fundacion.objects.filter(usuario=self.request.user)
		return context
	def get_queryset(self):		
		return Mascota.objects.filter(idfundacion=Fundacion.objects.get(usuario=self.request.user))


class SeleccionarMascota(ListView):

	model = Mascota
	template_name = 'fundacion/seleccionar.html'
	#queryset = Mascota.objects.filter(idfundacion="2")
	context_object_name = 'mascotas'
	paginate_by = 3

	def get_context_data(self, *args, **kwargs):
		context = super().get_context_data(*args, **kwargs)
		context['info'] = Fundacion.objects.filter(usuario=self.request.user)
		return context
	def get_queryset(self):		
		return Mascota.objects.filter(idfundacion=Fundacion.objects.get(usuario=self.request.user))


"""
class SeleccionarMascota(ListView):

	model = Mascota
	template_name = 'fundacion/seleccionar.html'
	#queryset = Mascota.objects.filter(idfundacion=Fundacion.objects.get(usuario=self.request.user))
	context_object_name = 'mascotas'
	paginate_by = 1

	def get_context_data(self, *args, **kwargs):
		context = super().get_context_data(*args, **kwargs)
		context['info'] = Fundacion.objects.filter(usuario=self.request.user)
		return context
	def get_query_set(self):		
		return Mascota.objects.filter(idfundacion=Fundacion.objects.get(usuario=self.request.user))
"""
class AgregarMascota(SuccessMessageMixin, CreateView):
	model = Mascota
	form_class = AgregarMascota
	template_name = 'fundacion/agregar.html'
	context_object_name = 'mascotas'
	success_message = "Mascota Agregada Correctamente!"

	def get_context_data(self, *args, **kwargs):
		context = super().get_context_data(*args, **kwargs)
		context['info'] = Fundacion.objects.filter(usuario=self.request.user)
		return context

	def form_valid(self, form):
		form.instance.idfundacion = Fundacion.objects.get(usuario=self.request.user)
		return super(AgregarMascota, self).form_valid(form)

	success_url = reverse_lazy('users:agregar')

class AgregarMulti(SuccessMessageMixin, CreateView):
	model = Contenido_Multi
	form_class = AgregarMultimedia
	template_name = 'fundacion/agregar_multi.html'
	context_object_name = 'multimedia'
	success_message = "Contenido Multimedia Agregado Correctamente!"

	def get_context_data(self, *args, **kwargs):
		context = super().get_context_data(*args, **kwargs)
		context['info'] = Fundacion.objects.filter(usuario=self.request.user)
		return context

	def form_valid(self, form):
		form.instance.id_mascota = Mascota.objects.get(id=self.kwargs['pk'])
		return super().form_valid(form)

	def get_success_url(self):
		id_mascota = self.kwargs['pk']
		return reverse_lazy('users:editar', kwargs={'pk': id_mascota})

class VerMultimedia(ListView):

	model = Contenido_Multi
	template_name = 'fundacion/multimedia.html'
	context_object_name = 'multimedia'
	paginate_by = 1

	def get_context_data(self, *args, **kwargs):
		context = super().get_context_data(*args, **kwargs)

		context['info'] = Fundacion.objects.filter(usuario=self.request.user)
		context['mascota'] = Mascota.objects.get(id=self.kwargs['pk'])
		return context
	def get_queryset(self):
		return Contenido_Multi.objects.filter(id_mascota=self.kwargs['pk'])
	

mysite/users/templates/adoptantes/catalogo.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<link rel="stylesheet" href="css/style.css" />
		<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
		<!-- nouislider -->
    	<link type="text/css" rel="stylesheet" href="css/nouislider.min.css" />
		<link
			href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,300;0,400;1,500&display=swap"
			rel="stylesheet"
		/>
		<link
			rel="stylesheet"
			href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css"
		/>
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap-theme.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
<style type="text/css">
</style>

		<title>Catálogo</title>


		<style>
			html {
				min-height: 100%;
				position: relative;
			}
						
			body {
				background-color: #f5f7fa;
				font-family: 'Roboto', sans-serif;
				margin: 0;
				margin-bottom: 10px;
			}
			.container {
				display: flex;
			}
			.side {
				min-width: 320px;
				height: 200px;
				background-color: #fff;
				height: 100%;
				min-height: 100vh;
				border-right: 3px solid #e1e1e1;
			}
			.content {
				width: 100%;
				display: flex;
				padding: 20px 0;
				align-items: center;
				flex-direction: column;

			}
			.side .header {
				background: linear-gradient(262deg, #ff7854, #fd267d);
				width: 100%;
				height: 150px;
				box-shadow: 0 1px 8px 0 rgba(0, 20, 20, 0.2);
				display: flex;
				align-items: center;
				padding: 0 1px;
			}

			.side .header .avatar img {
				width: 70px;
				height: 70px;
				border-radius: 100px;
				border: 3px solid #fff;
				box-shadow: 0 1px 8px 0 rgba(0, 20, 20, 0.2);
				margin: 0 18px;
			}

			.side .header .title {
				padding: 0 0.01px;
				color: #fff;
				font-size: 23px;
			}

			.side .menu ul {
				display: flex;
				padding: 0 20px;
			}

			.side .menu ul li {
				list-style: none;
				margin: 0 10px;
				font-weight: 700;
				font-size: 15px;
				letter-spacing: 0.5px;
			}

			.side .menu .active {
				border-bottom: 3px solid #fd5068;
				padding-bottom: 2px;
			}

			.side .messages {
				padding: 10px 20px;
				display: flex;
				align-items: center;
				transition: 0.2s box-shadow;
			}

			.side .messages .avatar img {
				width: 70px;
				height: 70px;
				border-radius: 70px;

			}

			.side .messages .avatar2 img {
				width: 120px;
				height: 70px;
				border-radius: 70px;
				margin: 0 -23px;


			}

			.side .messages .user {
				padding: 0 10px;
				font-weight: 500;
				letter-spacing: 0.5px;
				font-size: 18px;
			}

			.side .messages .text {
				width: 200px;
				white-space: nowrap;
				overflow: hidden;
				text-overflow: ellipsis;
				padding: 0 10px;
				font-weight: 300;
				font-size: 15px;
				opacity: 0.8;

			}

			.side .messages:hover {
				box-shadow: 0 0 15px 0 rgba(43, 78, 78, 0.1);
				border-right: 5px solid #0b76a6;
			}

			.container .card {
				position: relative;
				height: 320px;
			}

			.content .card .user {
				width: 320px;
				height: 350px;
				object-fit: cover;
				border-radius: 15px;
				box-shadow: 0 3px 10px 0 rgba(0, 20, 20, 0.5);
			}

			.content .card .user .profile {
				position: absolute;
				bottom: 0px;
				left: -20px;
			}

			.content .card .user .name {
				color: #030303;
				font-size: 32px;
				font-weight: 500;
				letter-spacing: 0.5px;
				margin: 0 70px;
			}

			.content .card .user .name span {
				font-size: -20px;
			}

			.content .card .local {
				display: flex;
				align-items: center;
				padding: 0 0 10px 0;

			}

			.content .card .local i {
				margin: 10px 10;
				color: #030303;
			}

			.content .card .local span {
				color: #030303;
				padding: 0 30px;
				text-shadow: 1px 1px 5px #444;
			}

			.content .buttons {
				margin-top:5px;
				display: flex;
				align-items: center;
			}

			.content .buttons .no i {
				color: #068e14;
				font-size: 50px;
			}


			.content .buttons .heart i {
				color: #fa0000;
				font-size: 50px;
			}

			.content .buttons .no,
			.content .buttons .heart {
				background-color: #d4cece;
				width: 70px;
				height: 70px;
				box-shadow: 0 1px 10px 0 rgba(0, 20, 20, 0.1);
				display: flex;
				justify-content: center;
				align-items: center;
				border-radius: 70px;
				margin: 30px;
				transition: 0.2s transform;
			}

			.content .buttons .no:hover,
			.content .buttons .heart:hover {
				transform: scale(1.1);
			}



			.define {

				width:980px;
				margin:0 auto;
       		}

       		#main-header {
				background: #c8c4c4;
				color: white;
				height: 80px;
			}	
			#main-header a {
				color: white;
			}

			/*
			 * Logo
			 */
			#logo-header {
				float: left;
				padding: 15px 0 0 20px;
				text-decoration: none;
			}
			#logo-header:hover {
				color: #0b76a6;
			}
			
			#logo-header .site-name {
				display: block;
				font-weight: 700;
				font-size: 1.2em;
			}
			
			#logo-header .site-desc {
				display: block;
				font-weight: 300;
				font-size: 0.8em;
				color: #060606;
			}
	

			/*
			 * Navegación
			 */
			nav {
				float: right;
			}
				nav ul {
					margin: 0;
					padding: 0;
					list-style: none;
					padding-right: 20px;
				}
				
					nav ul li {
						display: inline-block;
						line-height: 80px;
					}
						
						nav ul li a {
							display: block;
							padding: 0 10px;
							text-decoration: none;
						}
						
							nav ul li a:hover {
								background: #0b76a6;
							}

		</style>

	</head>
	<body>
		<header id="main-header">
		
		<a id="logo-header" href="#">
			<span class="site-name">Tu mascota</span>
			<span class="site-desc">¡Adopta hoy!</span>
		</a> <!-- / #logo-header -->

		<nav>
			<ul>
				<li><a href="{% url 'users:logout' %}">Cerrar sesión</a></li>
			</ul>
		</nav><!-- / nav -->

		</header><!-- / #main-header -->

		<div class="container">
			<div class="side">
				{%include 'adoptantes/profile_pop_up.html'%}
				<div class="messages">
					<div class="avatar">
						<img src="../../static/adoptantes/images/catalogo.jpg">
					</div>
					<div class="message">
						<a href="{% url 'users:main' %}" class="user">Catálago</a>
					</div>
				</div>
				<div class="messages">
					<div  class="avatar2">
						<img src="../../static/adoptantes/images/Match.jpeg">
					</div>
					<div  class="message">
						<a href="{% url 'users:list_match' %} " class="user" >Mis Match</a>
					</div>
				</div>
				
				
			</div>

			<div class="content">
				
				
				<div class="card">
					<div class="gallery">
						{%include 'adoptantes/carousel.html'%}
					</div>
					<div class="center">
         
						<div class="pagination">
				            {% if page_obj.has_previous %}
				              <a href="?page={{ page_obj.previous_page_number}}">&laquo;</a>
				            {% else %}
				              <a href="#">&laquo;</a>
				            {% endif %}

				            {% if page_obj.has_next %}
				              <a href="?page={{ page_obj.next_page_number}}">&raquo;</a>
				            {% else %}
				              <a href="#">&raquo;</a>
				            {% endif %}
				          </div>
				       </div>
				</div>
				
			</div>
		</div>
	</body>

<footer class="w3-container w3-teal w3-center w3-margin-top">
  <p>Creado por:</p>
  <p> Ana Maria Garcia, Leonardo Saez, Katherine Camacho, Andrès Felipe Delgado</p>

</footer>
    <!-- jQuery !-->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"> </script>
    <!-- jQuery UI !-->
    <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/themes/smoothness/jquery-ui.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>

</html>